<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class PluginMakeCommand extends Command
{
    protected $signature = 'plugin:make {name : The name of the plugin (e.g. WeatherPack)}';
    protected $description = 'Scaffold a new Anvig Plugin';

    public function handle()
    {
        $name = Str::studly($this->argument('name'));
        $path = app_path("Plugins/{$name}");

        if (File::exists($path)) {
            $this->error("Plugin {$name} already exists!");
            return;
        }

        // Create Directories
        File::makeDirectory($path, 0755, true);
        File::makeDirectory("{$path}/Tools", 0755, true);

        // Create Main Plugin Class
        $this->createPluginClass($name, $path);

        // Create Example Tool
        $this->createExampleTool($name, $path);

        $this->info("Plugin {$name} created successfully! 🚀");
        $this->info("Location: app/Plugins/{$name}");
    }

    protected function createPluginClass($name, $path)
    {
        $content = "<?php

namespace App\Plugins\\{$name};

use App\Plugins\PluginBase;
use App\Plugins\\{$name}\Tools\ExampleTool;

class {$name}Plugin extends PluginBase
{
    public function name(): string
    {
        return '{$name}';
    }

    public function description(): string
    {
        return 'Description for {$name}';
    }

    public function tools(): array
    {
        return [
            new ExampleTool(),
        ];
    }
}
";
        File::put("{$path}/{$name}Plugin.php", $content);
    }

    protected function createExampleTool($name, $path)
    {
        $content = "<?php

namespace App\Plugins\\{$name}\Tools;

use App\Services\Tools\ToolInterface;

class ExampleTool implements ToolInterface
{
    public function name(): string
    {
        return 'example_tool';
    }

    public function description(): string
    {
        return 'An example tool generated by the plugin CLI.';
    }

    public function parameters(): array
    {
        return [
            'type' => 'object',
            'properties' => [
                'input' => ['type' => 'string'],
            ],
            'required' => ['input'],
        ];
    }

    public function execute(array \$arguments): string
    {
        return 'You said: ' . \$arguments['input'];
    }
}
";
        File::put("{$path}/Tools/ExampleTool.php", $content);
    }
}
